### ISSUE TITLE
BIASRN%d keyword missing if the file is not bias subtracted

### ISSUE THREAD

**Issue by lucarizzi** [Keck-DataReductionPipelines/KCWI_DRP#1]
If there are no bias frames and the files are not bias subtracted, cosmic ray rejection stops because it cannot find BIASRN%d.

Sadly, this is the normal situation because we usually take Flats before we take biases, so the pipeline attempts to bias subtract the flats before we have a master bias, fails, never writes the BIASRN keywords.

**Comment by scizen9** [comment]
Commit 0707f43c651374b4b4188dadcaab53dc5994676c fixes this bug by using the OSCNRNx keyword if BIASRNx not available, and defaults to a value of 3 e- if neither of those are available.
