### ISSUE TITLE
Help with stacking science exposure datacubes

### ISSUE THREAD

**Issue by rgriffiths1947** [Keck-DataReductionPipelines/KCWI_DRP#111]
Are there any hints or help files associated with the stacking of datacubes taken with the 
identical instrument configuration, i.e. information
on how to build the appropriate header information for application to SAOImage DS9 ?

**Comment by MNBrod** [comment]
I would take a look at [cwitools](https://github.com/dbosul/cwitools), which is an external package that may or may not be of use. Aside from that, our pipeline ends at creating the reduced data, stacking/mosaicing needs to be handled by a third party.
