### ISSUE TITLE
wavelength differences between icube and icubew

### ISSUE THREAD

**Issue by lhaacke** [Keck-DataReductionPipelines/KCWI_DRP#140]
In the output from the pipeline I have noticed an wavelength offset in spectra taken from the icube and the icubew (same for icubed and icubes). The wavelengths are offset by about 6 pixels towards the redder end for any cube that has been wavelength corrected (see clip below), but this is far more than the heliocentric correction should be. Is there something going wrong in the wavelength correction?

I have compared the results to what I get from the ocubes cube when reducing with IDL, and the icube wavelength is consistent with that. My issue is with inconsistencies between the different python outputs.
I note that the sky subtraction has been modified, however, this is the same modification for all output cubes.

https://user-images.githubusercontent.com/122768730/222999100-1f7751e8-8246-40bc-afc7-649bce3b61a3.mov

Attached below are the spectra from icube.fits and icubew.fits I am comparing:
[spectra.zip](https://github.com/Keck-DataReductionPipelines/KCWI_DRP/files/10893587/spectra.zip)

**Comment by MNBrod** [comment]
With the roughest back-of-the-envelope math, each pixel is .25, so 6 pixels is about 1.5 A. The air-to-wavelength vacuum correction is ~1.4 A @ 5000. Could this be the unexpected offset we're seeing? If memory serves, the IDL pipeline does not do either helio/barycentric or air-to-vacuum corrections. 

If not, I'll keep looking for another bug!

**Comment by lhaacke** [comment]
Ah, yes, that does account for the shift, thank you! I had not realised that python does the air-to-vacuum correction.

**Comment by MNBrod** [comment]
Happy to help. If you'd like to turn off that correction, info on how to do so can be found at https://kcwi-drp.readthedocs.io/en/latest/configuration.html#wavelength-correction-parameters
