### ISSUE TITLE
Data product documentation

### ISSUE THREAD

**Issue by gannonjs** [Keck-DataReductionPipelines/KCWI_DRP#148]
Just pointing out that the pipeline now produces icubew files and there is no description as to what they are (barycentric corrected?)

It also produces files with multiple fits extensions which the old IDL pipeline does not. I think the documentation here needs an update:

https://kcwi-drp.readthedocs.io/en/1.0.1/data_products.html

**Comment by scizen9** [comment]
This will be updated when we make a release that includes a merge with the kcrm_merge branch.  It's already updated in the documentation repository: https://github.com/Keck-DataReductionPipelines/KCWI_DRP-Docs

**Comment by gannonjs** [comment]
Ok, thanks. A quick question:

Is there an easy way to view the updated documentation (in a readthedocs like format) without digging through the repo and trying to work out what things are where?

Otherwise you can feel free to close this request. It will fix itself at next release.

**Comment by scizen9** [comment]
The readthedocs has a 'latest' version which should work:
https://kcwi-drp.readthedocs.io/en/latest/data_products.html

Hope to do a full release within the next two weeks.
