### ISSUE TITLE
Pipeline not producing standard star calibrated data

### ISSUE THREAD

**Issue by gannonjs** [Keck-DataReductionPipelines/KCWI_DRP#151]
I've run the pipeline for both the red and blue arms and I am unable to get standard star calibrated data out (the icubes). I go through all of the fitting of the standard stars and the inversens are produced however these do not seem to be applying to the actual science data. The most advanced science product I can get out of the pipeline are the `cubed' files.

**Comment by scizen9** [comment]
Can you let me know which particular data set you are having trouble with?  What date and which science frames are not being calibrated?

**Comment by gannonjs** [comment]
The files are 20230915 (2023 Sept 15). We were second half, program W156 PI Forbes

**Comment by scizen9** [comment]
Unfortunately, you chose a very sparsely sample standard star.  In the DRP code, under the directory kcwidrp/data/stds you will see the reference fits files along with plots of the data.  If you look at the plot for Feige24, you'll see that there are only two points in common with your data and this is not enough to calibrate your data.  When I try to run it, the pipeline crashes and complains that there are only two points in common between the standard and your data.
![image](https://github.com/Keck-DataReductionPipelines/KCWI_DRP/assets/6845428/7d183d86-b22e-4a53-91dc-3db3f8bc9f6a)

**Comment by gannonjs** [comment]
It was failing not just in the red, but also in the blue. Have you been able to get the blue arm working?

Also, I have already contacted Rosalie on the standard stars for low flux in the red reasons, but standard stars that are not able to provide a solution for the red arm should be removed or at least they need to be noted in the standard star list somewhere.

**Comment by scizen9** [comment]
This standard will work for the low resolution gratings that span a larger wavelength range.  That is the purpose of the plots: to show where the wavelength samples are so observers can select a good standard for their specific configuration.

**Comment by scizen9** [comment]
I was able to successfully produce a flux calibration for the blue channel BL grating using Feige 25.  It's pretty low order, but in an emergency, it would be useful.  We will be sure to put in the documentation a request that observers check the plots in the pipeline before choosing a standard star.

**Comment by gannonjs** [comment]
I was also able to produce a fit for Feige 25 in the blue. My problem is
that the fit does not then go and apply to the other cubes. After fitting
the standard did your reduction then go on to produce 'icubes'?
