### ISSUE TITLE
Install instruction in README or readthedocs?

### ISSUE THREAD

**Issue by scizen9** [Keck-DataReductionPipelines/KCWI_DRP#16]
We need to list the Keck DRP framework as a dependency in the installation instructions with a command to install it, perhaps the git clone command?

**Comment by scizen9** [comment]
Also need to add cython dependency before the lacosmicx install

**Comment by scizen9** [comment]
The link to the readthedocs site points to a project node, not the documentation node.

Probably all we need to do is add the link to the framework docs.

**Comment by lucarizzi** [comment]
The link to the documentation is fixed.
I am not sure we want to maintain installation instructions in two different places (read the docs and readme), but if we want, I am happy to add the missing dependencies

**Comment by scizen9** [comment]
I agree.  Let's keep those dependencies in the readthedocs and remove them from the README.  Maybe the best would be to put a direct link to the install instructions in the README.  One other item, those readthedocs install instructions tell you how to install all the dependencies, but never tell you how to install KCWI_DRP.

**Comment by lucarizzi** [comment]
Wow 
Ok
I’ll fix them

**Comment by MNBrod** [comment]
Is this thread still active, or can it be closed?
