### ISSUE TITLE
hz43 is a binary

### ISSUE THREAD

**Issue by hgao-astro** [Keck-DataReductionPipelines/KCWI_DRP#168]
https://github.com/Keck-DataReductionPipelines/KCWI_DRP/blob/b1490671c2cf7228283e1ba674fcbf1be7d4a39f/kcwidrp/data/stds/kcwi_stds_starlist.txt#L40

Is it still a good candidate for use as a flux standard?

**Comment by MNBrod** [comment]
The starlist has been updated to remove HZ43, along with a few other variable stars. The list will be available from the KCWI webpage shortly, and can be viewed now at https://github.com/Keck-DataReductionPipelines/KCWI_DRP/blob/master/kcwidrp/data/stds/kcwi_stds_starlist.txt
