### ISSUE TITLE
add proper motion info to ross640

### ISSUE THREAD

**Issue by hgao-astro** [Keck-DataReductionPipelines/KCWI_DRP#169]
https://github.com/Keck-DataReductionPipelines/KCWI_DRP/blob/b1490671c2cf7228283e1ba674fcbf1be7d4a39f/kcwidrp/data/stds/kcwi_stds_starlist.txt#L50

the star has significant proper motions -494.230 and 746.698 mas/yr (https://simbad.u-strasbg.fr/simbad/sim-basic?Ident=ross640&submit=SIMBAD+search, GAIA EDR3). it would be handy for target acquisition to have the information in the list.

**Comment by MNBrod** [comment]
We have an update coming soon with PMs added for all entries in the standard list! This will be released shortly

**Comment by MNBrod** [comment]
We have updated the standards list to include PMs of all targets with Pull Request #170. The list will be up on the instrument page shortly, and is available now at https://github.com/Keck-DataReductionPipelines/KCWI_DRP/blob/master/kcwidrp/data/stds/kcwi_stds_starlist.txt

Thanks!
