### ISSUE TITLE
Offsets in the ThAr matching

### ISSUE THREAD

**Issue by gannonjs** [Keck-DataReductionPipelines/KCWI_DRP#171]
Looking at my reduced data for both the blue:

![arc_00020_ThAr_BL_Medium_atoff](https://github.com/Keck-DataReductionPipelines/KCWI_DRP/assets/21308585/8bd21b62-fade-44b8-b81b-46cf66b7a750)

and red:

![arc_00024_ThAr_RH3_Medium_atoff](https://github.com/Keck-DataReductionPipelines/KCWI_DRP/assets/21308585/1ef59458-96ab-4e98-8878-d3db24aae95b)

There seems to be quite a noticeable offset between the ref bar and the ATLAS that varies with wavelength. Is this something I should be worried about?

**Comment by scizen9** [comment]
No.  This is a preliminary offset and the plot is using a calculated dispersion that is not exact.  As long as the preliminary offset is close, the cross-correlation will find the correct offset and dispersion coefficients.  This looks fine.
