### ISSUE TITLE
cubes have large numbers of spikes

### ISSUE THREAD

**Issue by astronomeara** [Keck-DataReductionPipelines/KCWI_DRP#18]
Am comparing two cubes, one from the IDL pipeline, one from the python.
IDL: https://www.dropbox.com/s/wnjb1msi6ly0cil/kb190601_00055_icubed.fits?dl=0
Python: https://www.dropbox.com/s/biexygdafxaqwoq/kb190601_00055_icubed.fits?dl=0

The python cube has a large number of spikes (noise?) compared to the IDL.  Also, for the bright source near pixel 26,42 (qfitsview coordinates), there appears to be a weird feature in the python code (weird skysub?)

**Comment by MNBrod** [comment]
I believe this was attributed to some failure in cosmic ray rejection, which should be fixed by the swap to astroscrappy. Can you confirm that the spikes don't appear anymore? If so, I'll close this issue.

**Comment by astronomeara** [comment]
Con confirm for now.  Ok to close.
