### ISSUE TITLE
Does Clobber=True have meaning?

### ISSUE THREAD

**Issue by astronomeara** [Keck-DataReductionPipelines/KCWI_DRP#35]
Unless I understand incorrectly, setting Clobber=True is currently equivalent to saying 're-run the entire pipeline if something changes anywhere'

An example of this would be sky subtraction.  If I run the pipeline, realize I want to use a different sky frame, I think clobber=True just means 're-run the pipeline in full'.

**Comment by tylertucker202** [comment]
Using the term Clobber for re-run in a pipeline construction is a long shot from "to treat harshly" or "to hit hard". Changing Clobber to  'restartPipelineOnChange' .
