### ISSUE TITLE
Documentation should describe output files.  Split outputs as well

### ISSUE THREAD

**Issue by astronomeara** [Keck-DataReductionPipelines/KCWI_DRP#39]
Users won't know what is what otherwise.

Also, the ability to split the flux and variance files is needed for viewing in most IFU cube viewers (e.g. qfitsview)

**Comment by astronomeara** [comment]
Earlier comment about qfitsview is incorrect.  qfitsview loads just fine.  Nevertheless, a splitting option might be nice.  Low importance, though.

**Comment by geoffcfchen** [comment]
Hi I am also using the new KCWI pipeline and find that I have problems with the meaning of the output files as well. Are there any updates on the documentation?

**Comment by MNBrod** [comment]
Documentation has been updated with a table describing outputs. Split files request can be split into its own issue if we want to move forward with it.
