### ISSUE TITLE
Trouble with lacosmicx while using the KCWI reduction pipeline(python)

### ISSUE THREAD

**Issue by archanaaravindan** [Keck-DataReductionPipelines/KCWI_DRP#56]
Hello

I am trying to reduce the science images using the python version of the reduction pipeline, but I keep getting an error with lacosmicx. When I first installed the pipeline, there were separate instructions to install lacosmicx, but it isn't there anymore. I even tried uninstalling everything completely and reinstalling it again, but the same error crops up. 

Also, there seems to be some error with the gecko driver. I have to install it every time I run the reduction pipeline. I understand this is some path issue, but I'm unsure how to fix it. I have attached both the log files.

I would appreciate any help I could get to fix these issues. Thank you very much!

Archana

[DRPF.log](https://github.com/Keck-DataReductionPipelines/KCWI_DRP/files/6468751/DRPF.log)
[KCWI.log](https://github.com/Keck-DataReductionPipelines/KCWI_DRP/files/6468752/KCWI.log)

**Comment by MNBrod** [comment]
The lacosmicx issue is on us: we are about to remove it as a dependency, and we jumped the gun on removing the installation instructions. You can either install it manually (instructions below), or (what I would recommend), install kcwidrp directly from GitHub, following the [Installing For Development](https://kcwi-drp.readthedocs.io/en/latest/installing.html#installing-for-development) instructions. This will give you the most up-to-date version, which will be released on pip within the next few weeks.

To install lacosmicx:
`git clone https://github.com/cmccully/lacosmicx.git`
`cd lacosmicx`
`python setup.py install`

**Comment by archanaaravindan** [comment]
Thank you very much. I tried both ways, but the error persists.

**Comment by MNBrod** [comment]
Just to make sure we're on the same page, did you `pip uninstall kcwidrp` before installing from GitHub? If you could reply with the output to `which reduce_kcwi`, that would help identify which installation is being accessed.

As for the gecko driver issue, I'm taking a look into what might have caused that issue.

**Comment by archanaaravindan** [comment]
Oops! I did not uninstall kcwidrp before installing from GitHub. I did that, and now there aren't any errors related to lacosmicx! Thank you!

The error related to geckodriver is still there, though. If I try to install it with the `conda install -c conda-forge firefox geckodriver` command, I get that all requested packages are already installed.

Just for your reference, `which reduce_kcwi` returns /usr/local/bin/reduce_kcwi

**Comment by MNBrod** [comment]
I've been working on this for a while now, but unfortunately I haven't found a catch-all solution. I'll link a few threads from others with similar issues below, which include some troubleshooting steps that might work. There's something funky with bokeh (the plotting library we use) and its ability to find the drivers it needs to render images.

If you turn plotting off in the config file (instructions in the docs) it should help, although you'll lose all the diagnostic plots, which isn't ideal. Reply here if you have any updates. I'll keep working at it and let you know if I make any progress.

https://discourse.bokeh.org/t/missing-geckodriver-and-or-firefox-but-they-are-in-path/6776
https://github.com/bokeh/bokeh/issues/10108

**Comment by archanaaravindan** [comment]
I think the issue was with the ChromeDriver(my bokeh plots were displayed on Chrome). So I updated the driver and Chrome, and it seems to be working fine now. Thank you!
