### ISSUE TITLE
documentation of explaining the output files from KCWI DRP (python version)

### ISSUE THREAD

**Issue by geoffcfchen** [Keck-DataReductionPipelines/KCWI_DRP#57]
I use the new KCWI DRP to reduce the data. It outputs not only the xxx_icube.fits data cube but also XX_icubed.fits and XXX_icubew.fits. I am trying to understand what that means but I cannot find the explanation on the website (even in the old version here: https://github.com/Keck-DataReductionPipelines/KcwiDRP/blob/master/DATA_PRODUCTS). Do you know where I can find the documentation that explains all the output files? which one is the final datacube I should use? Thanks.

**Comment by lucarizzi** [comment]
Geoff,

I will make sure that we have a page describing this soon, but for the time being, here is the answer:

icubed has been corrected for differential atmospheric dispersion
icubew has been corrected for helio/barycentric correction and transferred to vacuum wavelengths
icubes has been flux calibrated if possible

so the answer to which cube you should use depends on whether or not you are applying the wavelength correction to vacuum and whether or not you are applying flux calibration.

If you are applying both, then the cube to use is icubes

**Comment by geoffcfchen** [comment]
Hi Luca,

In the output file, I only see 
kb210507_00037_icube.fits, 
kb210507_00037_icubed.fits
kb210507_00037_icubew.fits

I did not see icube**s**.fits file, so I am assuming that when you say icubes.fits, it means icube.fits?

**Comment by lucarizzi** [comment]
No I actually mean icubes. 
If you don’t see then it means you are not performing flux calibration which is ok. 
In this case your final output is the cubew
