### ISSUE TITLE
Install header listing scripts, wb.py and wr.py, in bin directory

### ISSUE THREAD

**Issue by scizen9** [Keck-DataReductionPipelines/KCWI_DRP#66]
Utility scripts wb.py and wr.py create header listings that are useful for planning the reduction.  Can be installed in conda environment bin directory without .py extension.

I believe this is a request to modify setup.py, but it may also involve other changes to pip bundle.

**Comment by MNBrod** [comment]
Leaving them as is, but not going to make them public.
