### ISSUE TITLE
environment.yml not consistent with requirements.txt

### ISSUE THREAD

**Issue by scizen9** [Keck-DataReductionPipelines/KCWI_DRP#96]
A fresh conda install using environment.yml gives more recent versions of some modules than are specified
in requirements.txt producing warnings in PyCharm.

- requests 2.26.0 (required ~=2.23.0)
- ccdproc 2.2.0 (required ~=2.1.0)

Might need to use >= instead of ~= in requirements.txt.

**Comment by MNBrod** [comment]
Fixed with #127.
